name: CI match microservice

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build Docker Image and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Si ton Dockerfile n'est pas à la racine, ajuste le chemin
          tags: ${{ secrets.DOCKER_USERNAME }}/matchs-fastapi:latest
          push: true  # Pousser l'image vers Docker Hub

  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install flake8
        run: pip install flake8

      - name: Run Flake8 Linter
        run: flake8 --max-line-length=120 --exclude=venv

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Docker Image for Testing
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/matchs-fastapi:latest

      - name: Run FastAPI Container for Tests
        run: |
          docker run -d -p 8000:8000 --name fastapi-container ${{ secrets.DOCKER_USERNAME }}/matchs-fastapi:latest
          sleep 5  # Attendre que le service démarre
          pytest /app/tests --junitxml=report.xml # Exécuter les tests dans le conteneur

      - name: Clean up
        run: |
          docker rm -f fastapi-container

  sonar-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Sonar Scanner
        run: |
          wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=matchs-fastapi \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
